#!/bin/bash

DIR=$( cd "$( dirname "$0" )/.." && pwd )

PYOUTPUT=$($DIR/pylibs/qm.py $@)
COUTPUT=$($DIR/bin/qm $@ 2>&1)

SOLUTION=$(echo -e "$PYOUTPUT" | grep "$(echo -e "$COUTPUT"| tail -1)")
if [ "$SOLUTION" == "" ]; then
    echo "INCORRECT"
else
    echo "CORRECT"
fi

echo "=============================================="
echo -e "options: -v$vars -o$m\n"
echo -e "    PY: \n$PYOUTPUT"
echo -e "----------------------------------------------"
echo -e "    C : \n$COUTPUT"
echo

