#!/bin/bash
input=$1
cat $input | sort -n -t, -k1,1 -k2,2 -k3,3 | uniq > ${input}.1

cat ${input}.1 | awk -F',' '{if (array[$1","$2] < $3) array[$1","$2]=$3} END { for (i in array) {print i"," array[i]}}' | sort -t, -n -k1,1 -k2,2 > ${input}.2

cat ${input}.2 | awk -F',' '{if (array[$2] < $3) array[$2]=$3} END { for (i in array) {print i"," array[i]}}' | sort -t, -n -k1,1 -k2,2 > ${input}.3
